# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_account',
            field=models.CharField(choices=[('paid', 'Paid'), ('referral', 'Referral')], default='buy', max_length=9),
        ),
    ]
