# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 08:53
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170924_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avt.png', null=True, upload_to=api.models.content_file_name),
        ),
    ]
