# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170924_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invite',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
