# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invite',
            field=models.IntegerField(default=0),
        ),
    ]
